version: '3.3'
services:
  backend:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
        context: ./backend
        dockerfile: ./Dockerfile
    command: yarn start:dev
    ports:
        - 3000:3000
        - 9229:9229
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    restart: unless-stopped
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'kronte-test'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: